# source: DIR
# destination: DIR
# safe: BOOL
# disable_disk_cache: BOOL
# ignore_theme_config: BOOL
exclude: README.md
# include: [DIR, FILE, ...]
# keep_files: [DIR, FILE, ...]
timezone: Europe/Rome
encoding: utf-8

theme: jekyll-theme-minimal
title: Mario's homepage
description: Bookmark this to keep an eye on my project updates!
