# source: [your repo's top level directory]
# destination: DIR
# safe: BOOL
# disable_disk_cache: BOOL
# ignore_theme_config: BOOL
exclude: README.md
# include: [DIR, FILE, ...]
# keep_files: [DIR, FILE, ...]
timezone: Europe/Rome
encoding: utf-8

title: Homepage di Mario
logo: /figures/20241010_115515_2_cut_rid1.jpg
description: Aggiungi questa pagina ai segnalibri per rimanere aggiornato sui miei progetti!
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
